# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild Demo_GitHub -t:rebuild -verbosity:diag -property:Configuration=Release -property:PublishProfile=C:/GitHub-Runner/YourPublishProfile.pubxml -property:OutputPath=C:/GitHub-Runner
    - name: Check
      run: |
        cd "C:\GitHub-Runner"
        dir
    - name: Run tests
      run: |
        vstest.console.exe "Demo_GitHub\Demo_GitHub.dll" /Platform:x64 /Framework:.NETFramework,Version=v4.5


